package com.github.jcustenborder.kafka.connect.client.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import org.immutables.value.Value;

import java.util.List;
import java.util.Map;

@Value.Style(jdkOnly = true)
@Value.Immutable
@JsonDeserialize(as = ImmutableCreateConnectorResponse.class)
public interface CreateConnectorResponse {
  /**
   * name (string) – Name of the created connector
   * config (map) – Configuration parameters for the connector.
   * tasks (array) – List of active tasks generated by the connector
   * tasks[i].connector (string) – The name of the connector the task belongs to
   * tasks[i].task (int) – Task ID within the connector.
   */
  @JsonProperty("name")
  String name();

  @JsonProperty("config")
  Map<String, String> config();

  @JsonProperty("tasks")
  List<TaskInfo> tasks();
}
